# Language
export LANG=en_US.UTF-8

# Command history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.config/zsh/zhistory

# Editor
export VISUAL=vim
export EDITOR=$VISUAL

# System PATH
PATH=/usr/local/bin:/usr/local/sbin:/usr/bin

# Node.js Python etc.
PATH=~/.local/bin:$PATH

# Ruby
PATH=~/.gem/ruby/2.7.0/bin:$PATH

# Golang
export GOPATH=~/.go
export GOBIN=$GOPATH/bin
PATH=$GOBIN:$PATH

# Rust
PATH=~/.cargo/bin:$PATH

# Plugin directory
export ENV_HOME=~/.config/env
export ZENV_HOME=$ENV_HOME/shell
export ZPLUGIN_HOME=$ZENV_HOME/plugin
