# Language
export LANG=en_US.UTF-8

# Command history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.local/share/zsh/zhistory

# Editor
export VISUAL=vim
export EDITOR=$VISUAL

# System and user PATH
PATH=~/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin

# Python
export PYENV_ROOT=~/.local/pyenv
PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init -)"

# Node
export NODENV_ROOT=~/.local/nodenv
PATH=$NODENV_ROOT/bin:$PATH
eval "$(nodenv init -)"

# Golang
export GOPATH=~/.local/go
export GOBIN=$GOPATH/bin
PATH=$GOBIN:$PATH

# Rust
export RUSTUP_HOME=~/.local/rustup
export CARGO_HOME=~/.local/cargo
PATH=$CARGO_HOME/bin:$PATH

# Config file location
export XDG_CONFIG_HOME=~/.config

# HTTPie
export HTTPIE_CONFIG_DIR=$XDG_CONFIG_HOME/httpie

# Custom
export ENV_HOME=$XDG_CONFIG_HOME/env
export ZENV_HOME=$ENV_HOME/shell
export ZPLUGIN_HOME=$ZENV_HOME/plugin
