# Language
export LANG=en_US.UTF-8

# Command history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.local/share/zsh/zhistory

# Editor
export VISUAL=vim
export EDITOR=$VISUAL

# System and user PATH
PATH=~/.local/bin:/usr/local/bin:/usr/local/sbin:/usr/bin:/usr/sbin

# Python
PATH=~/.pyenv/bin:$PATH
eval "$(pyenv init -)"

# Node
PATH=~/.nodenv/bin:$PATH
eval "$(nodenv init -)"

# Golang
export GOPATH=~/.go
export GOBIN=$GOPATH/bin
PATH=$GOBIN:$PATH

# Rust
PATH=~/.cargo/bin:$PATH

# Config file location
export XDG_CONFIG_HOME=~/.config

# HTTPie
export HTTPIE_CONFIG_DIR=$XDG_CONFIG_HOME/httpie

# Custom
export ENV_HOME=$XDG_CONFIG_HOME/env
export ZENV_HOME=$ENV_HOME/shell
export ZPLUGIN_HOME=$ZENV_HOME/plugin
