# Vi-mode
bindkey -v

# Python
export PYENV_ROOT=$XDG_DATA_HOME/pyenv
PATH=$PYENV_ROOT/bin:$PATH
eval "$(pyenv init --path)"
eval "$(pyenv init -)"

# Node
export NODENV_ROOT=$XDG_DATA_HOME/nodenv
PATH=$NODENV_ROOT/bin:$PATH
eval "$(nodenv init -)"

# Golang
export GOPATH=$XDG_DATA_HOME/go
export GOBIN=$GOPATH/bin
PATH=$GOBIN:$PATH

# Rust
export RUSTUP_HOME=$XDG_DATA_HOME/rustup
export CARGO_HOME=$XDG_DATA_HOME/cargo
PATH=$CARGO_HOME/bin:$PATH

# Powerlevel9k configuration
source $ZENV_HOME/p10k.zsh
source $ZPLUGIN_HOME/powerlevel10k/powerlevel10k.zsh-theme

# Completions
fpath=($ZPLUGIN_HOME/zsh-completions/src /usr/share/zsh/vendor-completions $fpath)

# Autosuggestions 
source $ZPLUGIN_HOME/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source $ZPLUGIN_HOME/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Fast syntax highlighting
source $ZPLUGIN_HOME/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Command-line fuzzy finder
source /usr/share/fzf/shell/key-bindings.zsh

# Compinit
source $ZENV_HOME/zstyle-completion
bindkey "${terminfo[kcbt]}" reverse-menu-complete
autoload -Uz compinit
compinit -d ~/.local/share/zsh/zcompdump

# Z jump around
eval "$(lua $ZPLUGIN_HOME/z.lua/z.lua --init zsh enhanced)"
export _ZL_DATA=~/.local/share/zsh/z

# Alias
alias sudo="sudo "
alias ls=lsd
alias ll="lsd -l"
alias la="lsd -la"
alias vi=nvim
alias vim=nvim
