# Vi-mode
bindkey -v

# Powerlevel9k configuration
source $ZENV_HOME/p10k.zsh
source $ZPLUGIN_HOME/powerlevel10k/powerlevel10k.zsh-theme

# Completions
fpath=($ZPLUGIN_HOME/zsh-completions/src $fpath)

# Autosuggestions 
source $ZPLUGIN_HOME/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source $ZPLUGIN_HOME/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Fast syntax highlighting
source $ZPLUGIN_HOME/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Z jump around
eval "$(lua $ZPLUGIN_HOME/z.lua/z.lua --init zsh)"
export _ZL_DATA=~/.config/zsh/z
export _ZL_MATCH_MODE=1

# Command-line fuzzy finder
source /usr/share/fzf/key-bindings.zsh
source /usr/share/fzf/completion.zsh

# Compinit
source $ZENV_HOME/zstyle-completion
autoload -Uz compinit
compinit -d ~/.config/zsh/zcompdump

# Alias
alias sudo='sudo '
alias pac=pacman
alias aur=yay
alias ls=lsd
alias ll="lsd -l"
alias la="lsd -la"
alias vi=nvim
alias vim=nvim
