right_format = """$cmd_duration$status$package$nodejs$rust$golang$lua$deno$kubernetes"""
add_newline = false

[line_break]
disabled = true

[status]
disabled = false

[sudo]
disabled = false

[character]
error_symbol = "[✗](bold red)"

[nodejs]
format = "[$symbol($version )]($style)"

[rust]
format = "[$symbol($version )]($style)"

[golang]
format = "[$symbol($version )]($style)"

[lua]
format = "[$symbol($version )]($style)"

[deno]
format = "[$symbol($version )]($style)"

[package]
format = "[$symbol$version]($style) "

[kubernetes]
disabled = false
format = '[$symbol$context( \($namespace\))]($style)'
