# Language
export LANG=en_US.UTF-8

# Command history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.temp/zhistory

# Editor
export VISUAL=vim
export EDITOR=$VISUAL

# System PATH
PATH=/usr/local/bin:/usr/bin:/bin:/usr/local/sbin:/usr/sbin:/sbin

# GNU core and tools
PATH=/usr/local/opt/make/libexec/gnubin:/usr/local/opt/binutils/bin:/usr/local/opt/coreutils/libexec/gnubin:$PATH
MANPATH=/usr/local/opt/coreutils/libexec/gnuman:$MANPATH

# LLVM
PATH=/usr/local/opt/llvm/bin:$PATH

# Ruby
PATH=/usr/local/opt/ruby/bin:$PATH

# PHP
PATH=~/.composer/vendor/bin:$PATH

# Rust
PATH=~/.cargo/bin:$PATH

# Golang
export GOPATH=~/.go
export GOBIN=$GOPATH/bin
PATH=$GOBIN:$PATH

# Export unique PATH
export -U PATH
export -U MANPATH

# Plugin directory
export ENV_HOME=~/.config/env
export ZENV_HOME=$ENV_HOME/Zshell
export ZPLUGIN_HOME=$ZENV_HOME/plugins
