# Environment variables
export ENV_HOME=~/.config/env
export ZENV_HOME=$ENV_HOME/Zshell
export ZPLUGIN_HOME=$ZENV_HOME/plugins

# Vi-mode
bindkey -v

# Command history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.temp/zhistory

# Powerlevel9k configuration
source $ZENV_HOME/powerlevel9k.zsh
source $ZPLUGIN_HOME/powerlevel9k/powerlevel9k.zsh-theme

# Completions
fpath=($ZPLUGIN_HOME/zsh-completions/src $fpath)

# Autosuggestions 
source $ZPLUGIN_HOME/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source $ZPLUGIN_HOME/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Fast syntax highlighting
source $ZPLUGIN_HOME/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Z jump around
eval "$(lua $ZPLUGIN_HOME/z.lua/z.lua --init zsh)"
export _ZL_DATA=~/.temp/z
export _ZL_MATCH_MODE=1

# Command-line fuzzy finder
[ -f ~/.temp/fzf.zsh ] && source ~/.temp/fzf.zsh

# Source general environment
source $ENV_HOME/profile
source $ZENV_HOME/zstyle-completion

# Compinit
autoload -Uz compinit
compinit -d ~/.temp/zcompdump

# Google cloud
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc
