# Vi-mode
bindkey -v

# Command history
export HISTSIZE=10000
export SAVEHIST=10000
export HISTFILE=~/.backup/zhistory

# Powerlevel9k configuration
source ~/.config/env/Zshell/powerlevel9k.zsh
source ~/.config/env/Zshell/plugins/powerlevel9k/powerlevel9k.zsh-theme

# Completions
fpath=(~/.config/env/Zshell/plugins/zsh-completions/src $fpath)

# Autosuggestions 
source ~/.config/env/Zshell/plugins/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source ~/.config/env/Zshell/plugins/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Fast syntax highlighting
source ~/.config/env/Zshell/plugins/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Z jump around
eval "$(lua $HOME/.config/env/Zshell/plugins/z.lua/z.lua --init zsh)"
export _ZL_DATA=~/.backup/z
export _ZL_MATCH_MODE=1

# Command-line fuzzy finder
[ -f ~/.backup/fzf.zsh ] && source ~/.backup/fzf.zsh

# Source general environment
source ~/.config/env/profile
source ~/.config/env/Zshell/zstyle-completion
