# Vi-mode
bindkey -v

# Powerlevel9k configuration
source $ZENV_HOME/p10k.zsh
source $ZPLUGIN_HOME/powerlevel10k/powerlevel10k.zsh-theme

# Completions
fpath=($ZPLUGIN_HOME/zsh-completions/src $fpath)

# Autosuggestions 
source $ZPLUGIN_HOME/zsh-autosuggestions/zsh-autosuggestions.zsh

# History substring search
source $ZPLUGIN_HOME/zsh-history-substring-search/zsh-history-substring-search.zsh
bindkey '^[[A' history-substring-search-up
bindkey '^[[B' history-substring-search-down

# Fast syntax highlighting
source $ZPLUGIN_HOME/fast-syntax-highlighting/fast-syntax-highlighting.plugin.zsh

# Z jump around
eval "$(lua $ZPLUGIN_HOME/z.lua/z.lua --init zsh)"
export _ZL_DATA=~/.temp/z
export _ZL_MATCH_MODE=1

# Command-line fuzzy finder
[ -f ~/.temp/fzf.zsh ] && source ~/.temp/fzf.zsh

# Compinit
source $ZENV_HOME/zstyle-completion
autoload -Uz compinit
compinit -d ~/.temp/zcompdump

# Google cloud
source /usr/local/Caskroom/google-cloud-sdk/latest/google-cloud-sdk/completion.zsh.inc

# Alias
alias ls=exa
alias ll="exa -l"
alias la="exa -la"
alias vi=nvim
alias vim=nvim
